[phases.setup]
nixPkgs = ["gcc", "sqlite", "sqlite.dev"]

[phases.install]
cmds = [
    "mkdir -p src/output",
    "gcc src/main.c src/functions.c -I src -o src/output/main -lsqlite3",
    "chmod +x src/output/main"
]

[phases.build]
cmds = ["echo Build complete"]