[phases.setup]
nixPkgs = ["gcc", "sqlite", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "mkdir -p src/output",
    "gcc src/main.c src/functions.c -I src -o src/output/main -lsqlite3",
    "chmod +x src/output/main"
]